### ISSUE TITLE
Segmentation fault on QCLEAR if no song is playing

### ISSUE THREAD

**Issue by rrrmiz** [SimonPersson/spotifyd#18] opened 2015-03-06 22:05 UTC
Hi,
Seems to be a problem in queue_clear(), where sp_track_release(cur_playing) is called even though cur_playing is NULL.
        Best Regards - Misi

**Comment by SimonPersson** [comment] 2015-03-06 22:06
My commit from yesterday fixes this, no?

**Comment by rrrmiz** [comment] 2015-03-06 22:17
Sorry, I am new to GitHub, and did not check. I downloaded two days ago.
Yes, it seems to work.
However, the QCLEAR does not seem to close the socket when it is done. It does not matter if a song is playing or not though, so it is not related to this. I have not investigated further.

**Comment by SimonPersson** [comment] 2015-03-07 10:56
No worries, just a coincidence that I ran into the same bug one day before you :)

I can't reproduce your other bug though. I will close this issue now, feel free to open up a new one when you have investigated the socket issue!

**Closed by SimonPersson** 2015-03-07 10:56 UTC
